spring:
  application:
    name: ye-ai-code-mother-backed
  profiles:
    active: dev


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ye.yeaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


